config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resource :session
  resource :registration
  resources :events
  resources :appointments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
# == Schema Information
#
# Table name: appointments
#
#  id             :bigint           not null, primary key
#  tickets_amount :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  event_id       :bigint
#  user_id        :bigint
#
# Indexes
#
#  index_appointments_on_event_id  (event_id)
#  index_appointments_on_user_id   (user_id)
#
class Appointment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                :bigint           not null, primary key
#  datetime          :datetime
#  description       :string
#  location          :string
#  name              :string
#  tickets_available :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Event < ApplicationRecord
  scope :upcoming, -> { where(datetime: Time.current..) }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  password_digest :string
#  username        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_username  (username) UNIQUE
#
class User < ApplicationRecord
  has_secure_password

  has_many :appointments, dependent: :destroy

  validates :username, presence: true
  normalizes :username, with: ->(username) { username.downcase }

  # TODO: Password reset
  # generates_token_for(:password_reset, expires_in: 10.minutes) { password_salt }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

  def current_user
    Current.user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def authenticate_user!
    return if user_signed_in?

    redirect_to new_session_path, alert: I18n.t("controllers.sessions.user_login_required")
  end

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(_user)
    Current.user = nil
    reset_session
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!

  # GET /appointments
  def index
    @appointments = current_user.appointments.includes(:event)
  end

  # POST /appointments
  def create
    result = ::Creators::AppointmentCreator.call(appointment_params)

    if result.success?
      redirect_to appointments_path, notice: I18n.t("controllers.appointments.purchase_successful")
    else
      flash[:alert] = I18n.t("controllers.appointments.purchase_failed")
      redirect_to event_path(result.record.event)
    end
  end

  private

  def appointment_params
    params.merge(user_id: current_user.id)
          .permit(:user_id, :event_id, :tickets_amount)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    result = ::Creators::UserCreator.call(user_params)
    @user = result.record

    if result.success?
      login(@user)
      redirect_to root_path, notice: I18n.t("controllers.registrations.user_created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    if User.authenticate_by(username: params[:username], password: params[:password])
      login User.find_by(username: params[:username])
      redirect_to root_path, notice: I18n.t("controllers.sessions.user_login")
    else
      flash[:alert] = I18n.t("controllers.sessions.user_login_failed")
      render :new, status: :unauthorized
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: I18n.t("controllers.sessions.user_logout")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/index.html.erb
<h1> My appointments </h1>


<h2> Current events </h2>
<ul>
  <% @appointments.each do |appointment| %>
  <li>
    <h3><%= link_to appointment.event.name, event_path(appointment.event) %></h3>
    <p><strong>date:</strong> <%= appointment.event.datetime %></p>
    <p>tickets: <%= appointment.tickets_amount %></p>
  </li>
  <% end %>
</ul>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.datetime %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Tickets available:</strong>
  <%= @event.tickets_available %>
</p>

<%= form_with url: appointments_path, method: :post do |form| %>
  <div class="field">
    <%= form.label :tickets_amount, "Number of Tickets: " %>
    <%= form.number_field :tickets_amount, min: 1, max: @event.tickets_available, value: 1 %>
  </div>
  <%= form.hidden_field :event_id, value: @event.id %>
  <div class="actions">
    <%= form.submit "Buy Tickets" %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1> Homepage </h1>

<% Rails.cache.fetch('cache_events_main', expires_in: 1.minute) do %>

  <h2> Current events </h2>
  <ul>
    <% Event.upcoming.each do |event| %>
    <li>
      <h3><%= link_to event.name, event_path(event) %></h3>
      <p><strong>Description:</strong> <%= event.description %></p>
      <p><strong>Location:</strong> <%= event.location %></p>
      <p><strong>Date and Time:</strong> <%= event.datetime.strftime("%B %d, %Y %I:%M %p") %></p>
      <p><strong>Tickets Available:</strong> <%= event.tickets_available %></p>
    </li>
    <% end %>
  </ul>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booking System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to "Log out", session_path, method: :delete %>
    <% else %>
      <div style="display: flex; gap: 10px;">
        <%= button_to "Log in", new_session_path, method: :get %>
        <%= button_to "Sign up", new_registration_path, method: :get %>
      </div>
    <% end %>

    <div style="display: flex; gap: 10px;">
      <%= link_to 'Main page', root_path %>
      <% if user_signed_in? %>
        <%= link_to 'My appointments', appointments_path %>
      <% end %>
    </div>

    <div> <%= notice %> </div>
    <div> <%= alert %> </div>

    <%= yield %>
  </body>
</html>